// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAgency.Models;

namespace TravelAgency.Migrations
{
    [DbContext(typeof(TravelAgencyContext))]
    [Migration("20220330204336_addReviewsUsers")]
    partial class addReviewsUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelAgency.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Tokyo",
                            Country = "Japan"
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Chicago",
                            Country = "USA"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "London",
                            Country = "England"
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Los Angelos",
                            Country = "Usa"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Sydney",
                            Country = "Australia"
                        });
                });

            modelBuilder.Entity("TravelAgency.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            DestinationId = 1,
                            Rating = 5,
                            Text = "Yolo",
                            UserId = 1
                        },
                        new
                        {
                            ReviewId = 2,
                            DestinationId = 2,
                            Rating = 3,
                            Text = "Awesome",
                            UserId = 1
                        },
                        new
                        {
                            ReviewId = 3,
                            DestinationId = 2,
                            Rating = 5,
                            Text = "Cool",
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 4,
                            DestinationId = 3,
                            Rating = 1,
                            Text = "Bad",
                            UserId = 1
                        },
                        new
                        {
                            ReviewId = 5,
                            DestinationId = 3,
                            Rating = 3,
                            Text = "Eh",
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 6,
                            DestinationId = 3,
                            Rating = 1,
                            Text = "Word",
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 7,
                            DestinationId = 4,
                            Rating = 4,
                            Text = "Radical",
                            UserId = 1
                        },
                        new
                        {
                            ReviewId = 8,
                            DestinationId = 4,
                            Rating = 4,
                            Text = "Cawabunga",
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 9,
                            DestinationId = 4,
                            Rating = 5,
                            Text = "Go there!",
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 10,
                            DestinationId = 4,
                            Rating = 5,
                            Text = "Do eet!",
                            UserId = 4
                        },
                        new
                        {
                            ReviewId = 11,
                            DestinationId = 5,
                            Rating = 4,
                            Text = "Rad",
                            UserId = 1
                        },
                        new
                        {
                            ReviewId = 12,
                            DestinationId = 5,
                            Rating = 5,
                            Text = "Nice",
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 13,
                            DestinationId = 5,
                            Rating = 4,
                            Text = "Da Bomb",
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 14,
                            DestinationId = 5,
                            Rating = 5,
                            Text = "Cool",
                            UserId = 4
                        },
                        new
                        {
                            ReviewId = 15,
                            DestinationId = 5,
                            Rating = 5,
                            Text = "Cool",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("TravelAgency.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Bob",
                            ReviewId = 0
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Mary",
                            ReviewId = 0
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Dakota",
                            ReviewId = 0
                        },
                        new
                        {
                            UserId = 4,
                            Name = "Riley",
                            ReviewId = 0
                        },
                        new
                        {
                            UserId = 5,
                            Name = "Sam",
                            ReviewId = 0
                        });
                });

            modelBuilder.Entity("TravelAgency.Review", b =>
                {
                    b.HasOne("TravelAgency.Destination", "Destination")
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAgency.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelAgency.Destination", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TravelAgency.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
